name: Build and Publish Package

on:
  push:
    tags:
      - '*'  # Trigger on any tag

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for changelog generation
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Make scripts executable
      run: |
        mkdir -p scripts
        cat > scripts/update_version.py << 'EOF'
        ${{ github.workspace }}/.github/scripts/update_version.py
        EOF
        cat > scripts/generate_changelog.sh << 'EOF'
        ${{ github.workspace }}/.github/scripts/generate_changelog.sh
        EOF
        chmod +x scripts/update_version.py scripts/generate_changelog.sh
    
    - name: Extract tag version
      id: get_version
      run: |
        # Get tag name and strip any 'v' prefix if present
        TAG=${GITHUB_REF#refs/tags/}
        VERSION=${TAG#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "TAG=$TAG" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: |
        uv pip install ruff pytest toml
        uv pip install -e .
    
    - name: Run linting
      run: |
        uv run ruff check .
    
    - name: Run tests
      run: |
        uv run pytest
    
    - name: Update version in pyproject.toml
      run: |
        uv pip install toml
        python scripts/update_version.py $VERSION
    
    - name: Generate changelog updates
      run: |
        bash scripts/generate_changelog.sh $TAG
    
    - name: Build package
      run: |
        uv build
        # uv pip install build
        # uv run python -m build
    
    - name: Publish to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        uv publish
        # uv pip install twine
        # uv run python -m twine upload --skip-existing --repository pypi dist/* -u __token__ -p $PYPI_API_TOKEN
    
    - name: Commit version and changelog updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pyproject.toml CHANGELOG.md
        git commit -m "Update version to $VERSION and changelog [skip ci]" || echo "No changes to commit"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${GITHUB_REF#refs/tags/}^{} || echo "No changes to push"